// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TextToSpeechHostApi {
  func speak(text: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopSpeaking(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TextToSpeechHostApiSetup {
  /// The codec used by TextToSpeechHostApi.
  /// Sets up an instance of `TextToSpeechHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TextToSpeechHostApi?) {
    let speakChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.speech_app.TextToSpeechHostApi.speak", binaryMessenger: binaryMessenger)
    if let api = api {
      speakChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        api.speak(text: textArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      speakChannel.setMessageHandler(nil)
    }
    let stopSpeakingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.speech_app.TextToSpeechHostApi.stopSpeaking", binaryMessenger: binaryMessenger)
    if let api = api {
      stopSpeakingChannel.setMessageHandler { _, reply in
        api.stopSpeaking() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      stopSpeakingChannel.setMessageHandler(nil)
    }
  }
}
